language: scala
scala:
- 2.11.7
jdk:
  - oraclejdk8
env:
- PLAY_VERSION=2.4.2
sudo: false
addons:
  apt:
    packages:
      - expect
before_script:
  - mysql -e 'create database gungnir_db;'
  - chmod +x ./opt/travis/travis_db_setup.sh
  - ./opt/travis/travis_db_setup.sh
script:
  - cd project-odin
  - ./activator test
